### ISSUE TITLE
Please tag release 1.0.1

### ISSUE THREAD

**Issue by simevo** [jonschlinkert/parse-filepath#6]
Hi the latest release (1.0.1) does not appear in the tags: https://github.com/jonschlinkert/parse-filepath/tags

Please tag this release and the future ones so that automatic upstream release monitoring works.

Thanks ! Paolo

**Comment by jonschlinkert** [comment]
please create specific issues, like "please tag release x.x.x".

**Comment by jonschlinkert** [comment]
done
