### ISSUE TITLE
ext with .tar.gz

### ISSUE THREAD

**Issue by MilesGG** [jonschlinkert/parse-filepath#7]
If you run the following code
```javascript
const parsePath = require('parse-filepath')

console.log(parsePath('examplefile.tar.gz'))
```
it will return this
```
{ root: '',
  dir: '',
  base: 'examplefile.tar.gz',
  ext: '.gz',
  name: 'examplefile.tar',
  extname: '.gz',
  basename: 'examplefile.tar.gz',
  dirname: '',
  stem: 'examplefile.tar',
  path: 'examplefile.tar.gz',
  absolute: [Getter/Setter],
  isAbsolute: [Getter/Setter] }
```
`ext` and `extname` should return .tar.gz and tar.xz also should function accordingly.

**Comment by doowb** [comment]
@MilesGG the results are correct. This library can be used as a replacement for the built-in node.js `path.parse` method, but also returns additional properties.

Both, `path.parse` and `path.extname` will also return `.gz` for the extension.
